SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DimCategory](
	[CategoryKey] [int] IDENTITY(1,1) NOT NULL,
	[Category] [nvarchar](128) NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DimCategory] ADD PRIMARY KEY CLUSTERED 
(
	[CategoryKey] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
ALTER TABLE [dbo].[DimCategory] ADD UNIQUE NONCLUSTERED 
(
	[Category] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

CREATE TABLE [dbo].[DimDate](
	[DateKey] [int] NOT NULL,
	[Date] [date] NOT NULL,
	[Year] [smallint] NOT NULL,
	[Quarter] [tinyint] NOT NULL,
	[MonthNumber] [tinyint] NOT NULL,
	[MonthName] [nvarchar](20) NOT NULL,
	[WeekOfYear] [tinyint] NOT NULL,
	[DayOfMonth] [tinyint] NOT NULL,
	[DayOfWeek] [tinyint] NOT NULL,
	[DayName] [nvarchar](20) NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DimDate] ADD PRIMARY KEY CLUSTERED 
(
	[DateKey] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

CREATE TABLE [dbo].[DimEntity](
	[EntityKey] [int] IDENTITY(1,1) NOT NULL,
	[EntityType] [nvarchar](64) NOT NULL,
	[EntityName] [nvarchar](512) NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DimEntity] ADD PRIMARY KEY CLUSTERED 
(
	[EntityKey] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
ALTER TABLE [dbo].[DimEntity] ADD  CONSTRAINT [UQ_DimEntity] UNIQUE NONCLUSTERED 
(
	[EntityType] ASC,
	[EntityName] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

CREATE TABLE [dbo].[DimOperation](
	[OperationKey] [int] IDENTITY(1,1) NOT NULL,
	[OperationName] [nvarchar](256) NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DimOperation] ADD PRIMARY KEY CLUSTERED 
(
	[OperationKey] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
ALTER TABLE [dbo].[DimOperation] ADD UNIQUE NONCLUSTERED 
(
	[OperationName] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

CREATE TABLE [dbo].[DimResource](
	[ResourceKey] [int] IDENTITY(1,1) NOT NULL,
	[ResourceId] [nvarchar](512) NOT NULL,
	[SubscriptionId] [nvarchar](64) NULL,
	[ResourceGroupName] [nvarchar](128) NULL,
	[ProviderNamespace] [nvarchar](128) NULL,
	[ResourceType] [nvarchar](256) NULL,
	[ResourceName] [nvarchar](256) NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DimResource] ADD PRIMARY KEY CLUSTERED 
(
	[ResourceKey] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
ALTER TABLE [dbo].[DimResource] ADD UNIQUE NONCLUSTERED 
(
	[ResourceId] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

CREATE TABLE [dbo].[DimSeverity](
	[SeverityKey] [int] IDENTITY(1,1) NOT NULL,
	[Severity] [nvarchar](64) NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DimSeverity] ADD PRIMARY KEY CLUSTERED 
(
	[SeverityKey] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
ALTER TABLE [dbo].[DimSeverity] ADD UNIQUE NONCLUSTERED 
(
	[Severity] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

CREATE TABLE [dbo].[DimSource](
	[SourceKey] [int] IDENTITY(1,1) NOT NULL,
	[Source] [nvarchar](32) NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DimSource] ADD PRIMARY KEY CLUSTERED 
(
	[SourceKey] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
ALTER TABLE [dbo].[DimSource] ADD UNIQUE NONCLUSTERED 
(
	[Source] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

CREATE TABLE [dbo].[DimStatus](
	[StatusKey] [int] IDENTITY(1,1) NOT NULL,
	[Status] [nvarchar](64) NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DimStatus] ADD PRIMARY KEY CLUSTERED 
(
	[StatusKey] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
ALTER TABLE [dbo].[DimStatus] ADD UNIQUE NONCLUSTERED 
(
	[Status] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

CREATE TABLE [dbo].[RawDiagnostics](
	[id] [bigint] IDENTITY(1,1) NOT NULL,
	[ingest_utc] [datetime2](3) NOT NULL,
	[source] [nvarchar](32) NOT NULL,
	[category] [nvarchar](128) NULL,
	[event_time_utc] [datetime2](3) NULL,
	[resource_id] [nvarchar](512) NULL,
	[operation_name] [nvarchar](256) NULL,
	[level] [nvarchar](32) NULL,
	[status] [nvarchar](64) NULL,
	[duration_ms] [bigint] NULL,
	[payload_json] [nvarchar](max) NOT NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[RawDiagnostics] ADD PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
CREATE NONCLUSTERED INDEX [IX_RawDiagnostics_category] ON [dbo].[RawDiagnostics]
(
	[category] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, DROP_EXISTING = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_RawDiagnostics_eventtime] ON [dbo].[RawDiagnostics]
(
	[event_time_utc] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, DROP_EXISTING = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[RawDiagnostics] ADD  DEFAULT (sysutcdatetime()) FOR [ingest_utc]
GO
